openapi: 3.0.1
info:
  title: Apex Copilot
  description: Apex Copilot is a plugin for Salesofrce Apex development.
  version: 'v1'
servers:
  - url: https://8d26-2001-9e8-1563-b00-5ddc-15fe-499d-1da1.ngrok-free.app/
paths:
  /info:
    get:
      summary: Get information about the plugin.
      description: Get information about the plugin.
      operationId: getInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                    description: The query that was sent to the plugin.
                  identity:
                    type: string
                    description: The identity of the user that sent the query
